#version: '3.8'

#services:
#  regent_server:
#    build: .
#    container_name: regent_server
#    restart: always
#    environment:
#      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
#      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
#    ports:
#      - "8080:8080"

version: '3.8'

services:
  regent_server:
    image: regent_server:latest
    container_name: regent_server
    restart: always
    env_file:
      - .env  # Добавляем ссылку на .env файл, который будет использоваться для переменных окружения
    ports:
      - "8080:8080"