version: "3"
services:
  regent_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: regent_server
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - /root/deploy_regent_server/.env
